//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaFabioOchoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_personal
    {
        public long ID_PERSONAL { get; set; }
        public string NOMBRE_COMPLETO { get; set; }
        public string CEDULA { get; set; }
        public System.DateTime FECHA_NACIMIENTO { get; set; }
        public byte ID_PROFESION { get; set; }
        public string DIRECCION { get; set; }
        public string MUNICIPIO { get; set; }
        public string TELEFONO { get; set; }
        public string SEXO { get; set; }
        public Nullable<byte> ID_VEHICULO { get; set; }
        public string MARCA { get; set; }
        public Nullable<long> MODELO { get; set; }
    
        public virtual tbl_profesion tbl_profesion { get; set; }
        public virtual tbl_vehiculos tbl_vehiculos { get; set; }
    }
}
